### ISSUE TITLE
doesn't work with ``requests`` library

### ISSUE THREAD

**Issue by pep8** [polymorphm/lib-socks-proxy#1]
the same code

```
from libsocks5 import monkey_patch as socks_proxy_monkey_patch
socks_proxy_monkey_patch.monkey_patch()

import requests
from libsocks5 import socks_proxy_context

with socks_proxy_context.socks_proxy_context(proxy_address=('2.2.2.2', 2222)):
    r = requests.get('http://httpbin.org/ip')
print(r.content)
```

works well on Windows7 (prints socks ip address), but doesn't work on ubuntu (prints ubuntu box ip address)

**Comment by pep8** [comment]
update:
on ubuntu works with standard python urllib, doesn't work with python requests.

**Comment by polymorphm** [comment]
confirmed this. does not work with `requests` library.

details:

```
GNU/Linux
requests version 2.5.1
Python version 3.4.2
```

**Comment by polymorphm** [comment]
I discovered that `requests` library has own implementation of `create_connection(...)`

site-packages/requests/packages/urllib3/util/connection.py

```
def create_connection(address, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
                  source_address=None, socket_options=None)
```

for fix this bug -- we need to write separate monkey_patch for this function too

**Comment by polymorphm** [comment]
thank you for this bug report @pep8 ! it will be fixed

**Comment by polymorphm** [comment]
@pep8 , I created support of ``requests`` in git-master-branch ( rev: c60a0a8 )

i tested it only my notebook (linux with details above).

may you test it, please ? thank you!

**Comment by pep8** [comment]
Confirm -
working on `Windows 7` `Python 3.4.0` `requests 2.2.1`
working on `Ubuntu 14.04.1 LTS` `Python 3.4.0` `requests 2.5.1`
Thank you!
